site_name: MoonLight

nav:
  - Home: index.md
  - General:
      - general/gettingstarted.md
      - general/customizingsveltekit.md
      - general/pull-requests.md
  - "MoonLight":
      - moonbase/module/animations.md
      - moonbase/module/artnet.md
  - "MoonBase":
      - moonbase/modules.md
      - moonbase/files.md
      - moonbase/module/instances.md
      - moonbase/module/demo.md
  - "Connections":
      - connections/mqtt.md
      - connections/ntp.md
  - "WiFi":
      - wifi/sta.md
      - wifi/ap.md
  - "System":
      - system/status.md
      - system/metrics.md
  - "ESP32 SvelteKit": 
      - esp32sveltekit.md
  - "Build Tools":
      - gettingstarted.md
      - buildprocess.md
  - "Front End":
      - sveltekit.md
      - structure.md
      - stores.md
      - components.md
  - "Back End":
      - statefulservice.md
      - restfulapi.md

site_author: ewowi
site_description: >-
  MoonLight is a fork of ESP32-SvelteKit and add Files, Modules, Light control and much more, ready to flash on ESP32 devices. This is a MoonModules.org project.

# Repository
repo_name: MoonModules/MoonLight
repo_url: https://github.com/MoonModules/MoonLight

theme:
  name: material
  logo: media/moonlight-logo.png
  favicon: media/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: indigo

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ewowi/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  analytics:
    provider: google
    property: G-R6QYDG0126

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

copyright: |
  Copyright &copy; 2024 by <a href="https://github.com/theelims"  target="_blank" rel="noopener">elims</a> -
  Copyright &copy; 2025 GPL-3.0 by <a href="https://github.com/ewowi"  target="_blank" rel="noopener">ewowi</a> -
  Copyright &copy; 2025 GPL-3.0 by <a href="https://github.com/MoonModules"  target="_blank" rel="noopener">MoonModules</a> -
  <a href="#__consent">Change cookie settings</a>
